### ISSUE TITLE
update needed

### ISSUE THREAD

**Issue by rschweigert** [nachocinalli/adapt-graphicExpand#2]
Hi Ignacio,

unfortunately this extension seems not to work anymore in AF 5.37.1.

Thanks in advance
Rainer

**Comment by nachocinalli** [comment]
Hi Rainer, I'm unable to replicate the error on version 5.37.1. 
Could you please provide more details or share an example so that I can analyze it further?

**Comment by rschweigert** [comment]
Of course.

I assume that this extension is intended for a graphic component. So, here is what I did:
```json
// components.json
{
    "_id": "c-165",
    "_parentId": "b-120",
    "_type": "component",
    "_component": "graphic",
    "_classes": "c-165",
    "_layout": "left",
    "title": "My graphic",
    "displayTitle": "",
    "body": "",
    "instruction": "",
    "_graphic": {
      "alt": "",
      "longdescription": "",
      "large": "course/de/images/arrangement-table.jpg",
      "small": "course/de/images/arrangement-table.jpg",
      "attribution": "",
      "_url": "",
      "_target": ""
    },
    "_graphicExpand": {
      "_isEnabled": true,
      "_button": {
        "buttonText": "zoom",
        "ariaLabel": "",
        "iconClass": "icon-expand_1"
      },
      "_selector": "c-165"
    }
}
```
But there is no expand-button in the image, no grunt build errors and no errors in ff dev-tools. What did I wrong?

**Comment by nachocinalli** [comment]
The _selector_ property allows indicating the selector used to insert the button. You can leave this property empty or specify a class. Examples:
```
"_selector": ""
"_selector": ".graphic__widget"
```

**Comment by rschweigert** [comment]
Great - thank you very much!
